export const EOF = 'EOF'
export const WHITESPACE = 'WHITESPACE'

export const SINGLE_LINE_COMMENT = 'SINGLE_LINE_COMMENT'
export const MULTI_LINE_COMMENT = 'MULTI_LINE_COMMENT'

export const MODULE_KEYWORD = 'MODULE_KEYWORD'
export const USE_KEYWORD = 'USE_KEYWORD'
export const STRUCT_KEYWORD = 'STRUCT_KEYWORD'
export const CLASS_KEYWORD = 'CLASS_KEYWORD'
export const ACTOR_KEYWORD = 'ACTOR_KEYWORD'
export const CONST_KEYWORD = 'CONST_KEYWORD'
export const INTERFACE_KEYWORD = 'INTERFACE_KEYWORD'
export const PRIVATE_KEYWORD = 'PRIVATE_KEYWORD'
export const PUBLIC_KEYWORD = 'PUBLIC_KEYWORD'
export const DELEGATE_KEYWORD = 'DELEGATE_KEYWORD'
export const STATIC_KEYWORD = 'STATIC_KEYWORD'
export const RETURN_KEYWORD = 'RETURN_KEYWORD'
export const IF_KEYWORD = 'IF_KEYWORD'
export const LET_KEYWORD = 'LET_KEYWORD'
export const OR_KEYWORD = 'OR_KEYWORD'
export const AND_KEYWORD = 'AND_KEYWORD'
export const NOT_KEYWORD = 'NOT_KEYWORD'
export const WAIT_KEYWORD = 'WAIT_KEYWORD'
export const AS_KEYWORD = 'AS_KEYWORD'
export const IS_KEYWORD = 'IS_KEYWORD'
export const TRUE_KEYWORD = 'TRUE_KEYWORD'
export const FALSE_KEYWORD = 'FALSE_KEYWORD'

export const PERIOD = 'PERIOD'
export const COLON = 'COLON'
export const COMMA = 'COMMA'
export const AT = 'AT'
export const FAT_ARROW = 'FAT_ARROW'
export const REVERSE_FAT_ARROW = 'REVERSE_FAT_ARROW'
export const FUNNEL = 'FUNNEL'
export const ARROW = 'ARROW'
export const STAR = 'STAR'
export const AMPERSAND = 'AMPERSAND'
export const PIPE = 'PIPE'
export const DOUBLE_QUOTE = 'DOUBLE_QUOTE'
export const SINGLE_QUOTE = 'SINGLE_QUOTE'
export const ESCAPED_CHAR = 'ESCAPED_CHAR'
export const DOUBLE_EQUALS = 'DOUBLE_EQUALS'
export const EQUALS_SIGN = 'EQUALS_SIGN'
export const PLUS_SIGN = 'PLUS_SIGN'
export const DASH = 'DASH'
export const SLASH = 'SLASH'
export const PERCENT_SIGN = 'PERCENT_SIGN'
export const CARET = 'CARET'

export const FLOAT_LITERAL = 'FLOAT_LITERAL'
export const INTEGER_LITERAL = 'INTEGER_LITERAL'

export const BEGIN_CURLY_BRACE = 'BEGIN_CURLY_BRACE'
export const END_CURLY_BRACE = 'END_CURLY_BRACE'
export const BEGIN_PAREN = 'BEGIN_PAREN'
export const END_PAREN = 'END_PAREN'
export const BEGIN_ANGLE_BRACKET = 'BEGIN_ANGLE_BRACKET'
export const END_ANGLE_BRACKET = 'END_ANGLE_BRACKET'
export const BEGIN_SQUARE_BRACKET = 'BEGIN_SQUARE_BRACKET'
export const END_SQUARE_BRACKET = 'END_SQUARE_BRACKET'

export const SYMBOL = 'SYMBOL'
export const UNKNOWN = 'UNKNOWN'
